export type WordCategory = { id: string; name: string; icon: string; words: string[] };

const words = (value: string) => value.trim().split(/\s+/);

// 1,000 palabras en 40 categorías. Se mantienen locales: no consumen base de datos ni red.
export const WORD_CATEGORIES: WordCategory[] = [
  { id: 'aeropuertos', name: 'Aeropuertos', icon: '✈️', words: words('terminal equipaje pasaporte aduana pista hangar vuelo piloto cabina asiento boleto escala salida llegada control radar torre avion maleta puerta embarque azafata retraso destino aeropuerto') },
  { id: 'casa', name: 'Casa', icon: '🏠', words: words('cocina comedor ventana puerta escalera pasillo terraza balcon sotano garaje techo pared suelo lampara cortina alfombra sillon mesa estante espejo cuadro timbre llave hogar') },
  { id: 'trabajo', name: 'Trabajo', icon: '💼', words: words('oficina reunion proyecto informe correo equipo cliente salario contrato horario agenda carpeta archivo llamada gerente colega empresa negocio tarea pausa ascenso empleo nomina entrevista') },
  { id: 'paises', name: 'Países', icon: '🌍', words: words('argentina chile brasil uruguay paraguay bolivia ecuador colombia venezuela panama mexico canada españa francia italia alemania portugal grecia japon china india turquia egipto marruecos australia') },
  { id: 'oceanos', name: 'Océanos y mar', icon: '🌊', words: words('pacifico atlantico indico artico antartico oceano corriente marea arrecife coral ballena delfin tiburon medusa pulpo calamar estrella concha oleaje espuma abismo nautico salino alga plancton') },
  { id: 'animales', name: 'Animales', icon: '🐾', words: words('elefante jirafa tigre leon pantera caballo conejo ardilla tortuga cocodrilo rinoceronte hipopotamo camello canguro koala mapache nutria lobo zorro ciervo gacela gorila mono jaguar leopardo') },
  { id: 'frutas', name: 'Frutas', icon: '🍓', words: words('manzana pera naranja mandarina pomelo limon banana platano fresa frambuesa arandano cereza durazno ciruela mango papaya sandia melon piña guayaba maracuya granada higo coco kiwi') },
  { id: 'verduras', name: 'Verduras', icon: '🥕', words: words('zanahoria tomate lechuga cebolla okra apio pepino calabaza brocoli coliflor espinaca acelga repollo remolacha berenjena pimiento puerro nabo rucula alcachofa esparrago champiñon batata yuca maiz') },
  { id: 'colores', name: 'Colores', icon: '🎨', words: words('amarillo naranja rojo carmesi rosa fucsia violeta morado lila azul celeste turquesa verde oliva esmeralda marron beige crema blanco negro gris plata dorado coral') },
  { id: 'cuerpo', name: 'Cuerpo humano', icon: '🫀', words: words('cabeza rostro frente ceja pestaña ojos nariz mejilla boca labio lengua diente oreja cuello hombro brazo codo muñeca mano dedo pecho espalda cintura rodilla tobillo') },
  { id: 'ropa', name: 'Ropa', icon: '👕', words: words('camisa blusa vestido falda pantalon chaqueta abrigo sueter sudadera camiseta pijama bufanda guante sombrero gorra cinturon calcetin zapato sandalia tacones botas corbata chaleco bermuda poncho') },
  { id: 'escuela', name: 'Escuela', icon: '📚', words: words('alumno maestro pizarra cuaderno lapiz borrador regla mochila recreo examen tarea lectura escritura numero ciencia historia geografia idioma musica arte deporte aula biblioteca diploma estudio leccion') },
  { id: 'deportes', name: 'Deportes', icon: '⚽', words: words('futbol beisbol tenis voleibol baloncesto natacion ciclismo atletismo boxeo karate judo esgrima golf rugby hockey patinaje gimnasia surf remo buceo escalada maraton carrera salto arquero') },
  { id: 'musica', name: 'Música', icon: '🎵', words: words('melodia ritmo armonia cancion guitarra piano violin trompeta bateria flauta saxofon arpa cello tambor concierto artista cantante coro banda sonido nota escala acorde compas verso estribillo') },
  { id: 'cine', name: 'Cine', icon: '🎬', words: words('pelicula actor actriz director guion escena camara rodaje estreno entrada pantalla butaca palomitas drama comedia terror accion romance aventura fantasia documental premio doblaje subtitulo trailer') },
  { id: 'tecnologia', name: 'Tecnología', icon: '💻', words: words('internet teclado pantalla raton codigo programa archivo carpeta servidor nube enlace pagina navegador correo mensaje camara telefono tableta robot sensor bateria cable puerto redes dato memoria usuario') },
  { id: 'espacio', name: 'Espacio', icon: '🚀', words: words('planeta estrella galaxia cometa meteoro asteroide satelite cohete astronauta orbita eclipse crater luna tierra marte venus jupiter saturno urano neptuno mercurio universo cosmos nebulosa gravedad') },
  { id: 'clima', name: 'Clima', icon: '⛅', words: words('lluvia tormenta trueno relampago viento brisa huracan tornado nieve granizo niebla nube arcoiris sequia humedad calor frio helada rocio clima verano invierno otoño primavera pronostico') },
  { id: 'transporte', name: 'Transporte', icon: '🚗', words: words('automovil autobus camion tren metro tranvia bicicleta motocicleta patinete taxi barco lancha ferry avion helicoptero cohete tractor grua ambulancia carreta vagon volante motor rueda camino viaje') },
  { id: 'ciudad', name: 'Ciudad', icon: '🏙️', words: words('avenida calle plaza parque edificio semaforo acera puente tunel estacion museo teatro hospital escuela mercado tienda banco hotel iglesia fabrica barrio centro suburbio monumento fuente kiosco') },
  { id: 'campo', name: 'Campo', icon: '🌾', words: words('granja establo tractor cosecha semilla cultivo trigo cebada maiz pradera molino granero huerto ganado pastor oveja vaca gallina caballo cerdo cerca pozo sendero colina arroyo') },
  { id: 'playa', name: 'Playa', icon: '🏖️', words: words('arena sombrilla toalla bañador bikini protector bronceado palmera cocotero concha caracola cangrejo gaviota oleaje marea costa bahia puerto velero tabla surf castillo cubo pala hamaca horizonte') },
  { id: 'montaña', name: 'Montaña', icon: '🏔️', words: words('cumbre ladera valle sendero refugio mochila cuerda brujula mapa escalada roca nieve glaciar pino abeto aguila cabra cascada torrente bosque acantilado altura cima excursion barranco') },
  { id: 'selva', name: 'Selva', icon: '🌴', words: words('tropical liana palmera helecho orquidea bambu jaguar tucan loro mono gorila serpiente rana insecto mariposa hormiga cascada humedad follaje tronco raiz copa sombra explorador tribu riachuelo') },
  { id: 'desierto', name: 'Desierto', icon: '🏜️', words: words('arena duna oasis cactus camello escorpion serpiente lagarto sequia espejismo caravana nomada calor solar sombra cantimplora horizonte tormenta roca cañon meseta huella refugio palmera travesia') },
  { id: 'cocina', name: 'Cocina', icon: '🍳', words: words('sarten olla cuchillo tenedor cuchara plato vaso taza horno nevera congelador batidora tostadora licuadora colador rallador tabla bandeja mantel servilleta especia receta fuego vapor cocina fregadero') },
  { id: 'baño', name: 'Baño', icon: '🛁', words: words('ducha bañera lavabo espejo toalla jabon champu cepillo pasta peine esponja grifo agua vapor cortina alfombra inodoro papel secador colonia crema locion estante azulejo higiene') },
  { id: 'dormitorio', name: 'Dormitorio', icon: '🛏️', words: words('cama almohada sabana manta colchon cabecera armario ropero comoda cajon espejo lampara mesita cortina ventana despertador pijama pantufla percha cuadro alfombra techo pared puerta descanso') },
  { id: 'jardin', name: 'Jardín', icon: '🌻', words: words('flor rosa tulipan margarita girasol jazmin violeta orquidea planta semilla tierra maceta regadera manguera pala rastrillo cesped arbusto arbol fuente banco mariposa abeja caracol jardin') },
  { id: 'herramientas', name: 'Herramientas', icon: '🧰', words: words('martillo clavo tornillo tuerca llave alicate tenaza serrucho taladro broca lima cincel pala pico hacha nivel cinta metro escuadra pinza sierra destornillador yunque cepillo herramienta') },
  { id: 'profesiones', name: 'Profesiones', icon: '👩‍⚕️', words: words('medico enfermera abogado maestro arquitecto ingeniero cocinero panadero bombero policia piloto artista musico escritor periodista dentista veterinario mecanico carpintero jardinero fotografo actor diseñador cientifico contador') },
  { id: 'emociones', name: 'Emociones', icon: '😊', words: words('alegria tristeza miedo sorpresa enojo calma orgullo ternura esperanza nostalgia gratitud confianza ansiedad cariño entusiasmo verguenza alivio curiosidad admiracion serenidad euforia paciencia empatia ilusion deseo') },
  { id: 'amor', name: 'Amor', icon: '❤️', words: words('pareja abrazo beso cariño ternura romance cita detalle regalo carta flores alianza promesa confianza respeto apoyo sonrisa mirada complicidad aventura recuerdo hogar futuro juntos amistad pasion') },
  { id: 'viajes', name: 'Viajes', icon: '🧳', words: words('maleta pasaporte boleto reserva hotel hostal mapa ruta destino turista guia excursion aventura paisaje recuerdo fotografia equipaje tren avion barco carretera frontera moneda idioma cultura llegada salida') },
  { id: 'historia', name: 'Historia', icon: '🏺', words: words('imperio reino corona batalla tratado castillo muralla ejercito general reyes reina faraon piramide templo colonia conquista revolucion independencia republica siglo epoca archivo reliquia pasado cronica') },
  { id: 'ciencia', name: 'Ciencia', icon: '🔬', words: words('atomo molecula celula energia materia fuerza masa volumen teoria formula ensayo muestra laboratorio microscopio telescopio planeta especie evolucion genetica quimica fisica biologia geologia invento') },
  { id: 'medicina', name: 'Medicina', icon: '🩺', words: words('doctor paciente hospital clinica receta vacuna jarabe pastilla vendaje herida fiebre gripe dolor pulso sangre examen terapia cirugia farmacia salud cuidado sintoma diagnostico remedio descanso') },
  { id: 'comida', name: 'Comida', icon: '🍽️', words: words('arroz pasta sopa ensalada carne pollo pescado huevo queso panes pizza hamburguesa tortilla empanada arepa tamal sushi curry lasaña guiso sandwich croqueta postre desayuno almuerzo cena') },
  { id: 'bebidas', name: 'Bebidas', icon: '🥤', words: words('agua cafe matcha leche jugo limonada refresco batido chocolate cerveza vino sidra coctel ponche infusión mate horchata granizado gaseosa capuchino espresso mocaccino licuado mineral tropical') },
  { id: 'fiestas', name: 'Fiestas', icon: '🎉', words: words('cumpleaños navidad carnaval pascua boda aniversario reunion musica baile pastel vela regalo globo confeti sorpresa invitado brindis abrazo fotografia decoracion disfraz piñata tarjeta recuerdo celebracion') },
];

export const WORD_COUNT = WORD_CATEGORIES.reduce((total, category) => total + category.words.length, 0);

export function wordCategory(id: string) {
  return WORD_CATEGORIES.find((category) => category.id === id) ?? WORD_CATEGORIES[0];
}
